### ISSUE TITLE
Chrome で他の言語のページと認識される可能性がある

### ISSUE THREAD

**Issue by tac-ichiro** [TachikawaAkebonochoClub/gekokujo#22]
![image](https://user-images.githubusercontent.com/46436877/176580810-831ed651-36dd-4b10-8604-99a04e51a1cb.png)

明示的に言語＝日本語を指定できないか？

**Comment by nakazawaaoi** [comment]
base.htmlに
<html lang="ja">
を宣言コードの下に書きました。
