### ISSUE TITLE
苦手キーがない場合の扱い方

### ISSUE THREAD

**Issue by ishii-miki** [TachikawaAkebonochoClub/gekokujo#8]
現状、nullを許可しているため、苦手キーなしの場合に未入力（表示される際は「none」）と「0」が混ざっている。

**Comment by ishii-miki** [comment]
- [ ] Djangoとpostgresのnullの取り扱いについて調査

**Comment by nakazawaaoi** [comment]
djangoではCharFieldを空で保存されるとNullではなく空文字で保存される。また、null = Trueを使用するのは避けたほうが良いらしいため、今回はmodels.pyの苦手キーのCharFieldから blank=True, null=Trueを削除した。
そのため、苦手キーがなかった場合、入力フォームでは0を入力してもらうことで解決した。
